### ISSUE TITLE
Get current user uid and use it to create user collection

### ISSUE THREAD

**Issue by benyass002** [benwinding/react-admin-firebase#146]
Hi,

I'd like to be able to set my resource collection based on the logged in user uid , 
I need to set **rootRef** dynamically based on the logged in user.

i tried using **localStorage** with no success .

my code :

  const authProvider = FirebaseAuthProvider(config,Authoptions);     

  

  var currentUser = JSON.parse(localStorage.getItem('firebase:authUser:#######################":[DEFAULT]') || '{}');
    
  var options = {
    logging: true,
    rootRef: '/' + currentUser +'/some_document'
  }

Thanks!

**Comment by acbrimer** [comment]
Hey benyass002,

I was able to achieve something similar by creating a "super" data provider based on this article: https://blog.theodo.com/2019/04/react-admin-second-api/

Best solution I've come up with for my use case is to hard-code an array with the resources that belong to my parent document (the profile for the current user) to check against when the super data provider is called. If the array includes the resource being called, the super provider returns FirebaseDataProvider with rootRef set to the path for the parent document. Otherwise, super provider returns FirebaseDataProvider with rootRef = '/'.

So far, I haven't found any limitations with this method aside from having to hard-code the array in my super data provider.
Here's the code I'm using to create my dataProvider: 
`const student_profile_subroutes = ['assessments', 'assignments', 'recordings'];
const dataProvider = (type, resource, params) => {
  let provider = FirebaseDataProvider(config, options);
  if (student_profile_subroutes.includes(resource)) {
    const profile_id = localStorage.getItem('profile_id');
    provider = FirebaseDataProvider(config, {
      rootRef: `student_profiles/${profile_id}`,
      ...options
    });
  }
  return provider(type, resource, params);
};`

Hope this helps!
-AB

**Comment by benyass002** [comment]
thank you i will surely give it a try !
