### ISSUE TITLE
DateInput is stored as String

### ISSUE THREAD

**Issue by amaljoe** [benwinding/react-admin-firebase#201]
Timestamp object in firestore is read correctly as date and is showing date input for that field. But if I change the value and save, it is getting stored as String in the format 2021-02-05. Is it supposed to be like that? It should be a timestamp object, right?

**Comment by amaljoe** [comment]
Using DateTImeInput solved the issue. But it also shows the time even though I dont want to show it to the user. So it will be better if it could work for the DateInput too.

**Comment by benwinding** [comment]
Sorry for the late reply, this is due to the `DateInput` component in the [ra-ui-materialui](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/DateInput.tsx#L62-L67), not this library. But here's the solution anyway:
## Solution
In order to use the `DateInput` with the Javascript `Date` object, you need to add a `parse` function like this:
``` jsx
      <DateInput source="date" parse={val => new Date(val)} />
```

**Comment by amaljoe** [comment]
> Sorry for the late reply, this is due to the `DateInput` component in the [ra-ui-materialui](https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/input/DateInput.tsx#L62-L67), not this library. But here's the solution anyway:
> 
> ## Solution
> In order to use the `DateInput` with the Javascript `Date` object, you need to add a `parse` function like this:
> 
> ```js
>      // Will always be a Date object
>      <DateInput source="date" parse={val => new Date(val)} />
> ```

Oh thats helpful. Thank you.
