### ISSUE TITLE
Question - Using Firebase Functions

### ISSUE THREAD

**Issue by mermicode** [benwinding/react-admin-firebase#206]
Hi there, sorry for raising my question on here - couldn't find any answers in docs or google.

I just wanted to ask, has anyone customised this to work with Firebase Functions? I have a number of Declarative Firebase Functions that act as middleware and business logic between my client and Firestore and want the App to interact with Firestore always by using Firebase Functions. Does anyone have any suggestions?

Many thanks! :)

**Comment by shreyas-jadhav** [comment]
I'm working on a package which should allow you to provide this functionality. I just started it yesterday and I'm looking for contributors who can help speed up the development. I have got bare amount of things working like returning the actual Firebase Users from Admin SDK. But nothing near to be usable in actual projects.

https://github.com/shreyas-jadhav/ra-next-firebase-provider

Most welcome to any contributors. And a huge thanks in advance.

**Comment by benwinding** [comment]
Hi There,
This library does not use firebase functions and directly talks to the firestore database from the client. If you want middleware functions, you could perform the logic on the client by wrapping the data provider, otherwise you need to use another server and probably something like `ra-data-json-server` to access it.

https://github.com/marmelab/react-admin/blob/master/packages/ra-data-json-server/README.md
