### ISSUE TITLE
Image upload size meta information

### ISSUE THREAD

**Issue by alexookah** [benwinding/react-admin-firebase#264]
Is it possible to save as metadata information the width and height of every image that gets uploaded to storage?
Having the image dimensions information would be great.

**Comment by KonkretneKosteczki** [comment]
`react-admin` itself does not support adding custom props to the FileInput or ImageInput. This would require creating custom Inputs to work with the dataProvider. I would argue this is a bad practice since swapping the dataProvider in the future would be impossible in such a case.

How about adding a firebase function that would automatically add required metadata on storage object finalize trigger? Something similar to this: https://github.com/firebase/functions-samples/blob/main/exif-images/functions/index.js

**Comment by alexookah** [comment]
Yeah. You are right!
Thanks for the detailed response
