### ISSUE TITLE
DateTime and Date gets updated as string instead of timestamp

### ISSUE THREAD

**Issue by Input8** [benwinding/react-admin-firebase#40]
On any form with Date or DateTime input fields data usually is set as timestamp. This works as long as there is new input (like on a create form or and edit form as long as you actually edit these fields). It happens that if you don't change the input of these fields  it gets updated (which it shouldn't in the first place as it wasn't changed) and gets updated as string.

**Comment by benwinding** [comment]
Hi @Input8,

Thanks for checking out the library, not sure I can understand your issue though, can you elaborate a bit more with an example perhaps?

Just some background, Firestore does not allow a `Date` object to be stored in the database, and will automatically convert it to a `Timestamp` object when it is sent to the database.

Let me know some more details and I'll try and help out.

Cheers,
Ben

**Comment by benwinding** [comment]
Okay, upon closer inspection it seems you're saying that the default input for a `Date` or `DateTime` is entered as a string, if no input is given to the form. 

This is a good point, and perhaps `null` should be passed into the property instead of a string, which would remove the value from the Firestore document. I'll look at implementing this and update this issue :+1:
