### ISSUE TITLE
High Reads

### ISSUE THREAD

**Issue by 0zguner** [benwinding/react-admin-firebase#59]
I have around 5000 records. Reads climbs up 5K everytime opening dashboad

**Comment by benwinding** [comment]
Yes that's true, this library pulls the whole collection on load.

We may implement a feature to allow paging (using the firebase sdk `limit` feature) but the trade-off is that you lose fuzzy searching (each search needs to be an exact match on a field...

**Comment by LaszloDev** [comment]
I'm suggesting to two things:
- Provide a setting to only lazy load the amount of items per page that are set by the "Rows per page" option.
- Optionally: if the lazy load is activated, note the user, when entering a search query, that all data will now be loaded and can locally searched

This way we can reduce the amount of data loading, because some users even don't have the search activated.

**Comment by benwinding** [comment]
> - Provide a setting to only lazy load the amount of items per page that are set by the "Rows per page" option.
> - Optionally: if the lazy load is activated, note the user, when entering a search query, that all data will now be loaded and can locally searched
>
> This way we can reduce the amount of data loading, because some users even don't have the search activated.

That's a good point @LaszloDev, lazy loading would solve this issue.

There are 2 road blocks to implementing this though. 

1. **Pagination count** - Firestore, doesn't allow you to query the size of a collection, so we have no idea how many pages in the table there are. 
![image](https://user-images.githubusercontent.com/11782590/69002644-1cde2200-0943-11ea-88ac-d51eca366c65.png)
To solve this, we could make it like 1000 pages in lazyloading mode. This is not a big deal but could be confusing for the user.

2. **Pagination in general** - Pagination is tricky in Firestore, it's possible using [Query Cursors](https://firebase.google.com/docs/firestore/query-data/query-cursors) but isn't trivial.

This is definitely something we need to solve for any system with any real data sets. 

Let me know your thoughts,

Cheers,
Ben

**Comment by agentlewis** [comment]
Firstly 🙌🙏🤗 for the great work so far! I'm very much looking forward to using this in my first personal project in an age!

Ok so I went through the code and I think I have  an idea of how it works. Can I clarify if these two understandings are correct:

 - All data once fetched from firestore is stored in the redux store inside react-admin.
 - The lazy search function is operating on the data in the redux store.

If these two understandings are correct then I would suggest the following:

We (royal) should look at some how wrapping the [firestore query operator](https://firebase.google.com/docs/firestore/query-data/queries)  for the search feature.

Then when a user enters a search we show the immediate results found in the redux store, show a spinner somewhere (maybe in the top right of the menu) to indicate data is being fetched and fore off the search through the firestore query. Once it comes back with results these should be added to the redux store and should automatically trigger a render and appear in the results.

The advantage of this approach is we dont have to load extra records on load. We also give users an optimistic update of the results and lastly in actually think this is the behaviour a user would expect from an app.

The cons of this approach are basically that we would need to suss out how wrap the query code to make it work in a "fuzzy" way.

--- 

**Beware scope creep below!**

An additional nice to have could be to iplement @resource-types and #resource-tags into it.

so in could then go "@invoice #paid boom inc" and perhaps the @ and # would be auto completed.

...sorry I'm just dreaming - obviously such a system would need to assume there was a collection of collection types and that all records had tags. But it would be cool ;)

**Comment by benwinding** [comment]
Hi @agentlewis, 
Thanks for your interest in the project! 
Yes, you've discovered the limitations of Firestore and consequentially this library. The only way to search documents in Firestore is either:

- Pull the entire collection and search it on the client (High reads, not performant).
- Use strict searching through the firestore query api (No fuzzy searching)

> An additional nice to have could be to iplement @resource-types and #resource-tags into it.
  So I could then go "\@Invoice #paid boom inc" and perhaps the @ and # would be auto completed.

That's an interesting idea, I think we discussed it earlier in the year. But it could be a good way forward.

> ...sorry I'm just dreaming - obviously such a system would need to assume there was a collection of collection types and that all records had tags. But it would be cool ;)

See initially I was hesitant to make this an opinionated framework, and wanted in to be as simple and *plug-n-play* as possible.... but to add features like scalable fuzzy searching and autocomplete. There needs to be extra steps (indexes, firestore hooks etc...) Maybe we should implement a plan to make this possible?

**Comment by agentlewis** [comment]
@benwinding I thought about this some more overnight and here is what I came to.

I would be planning to use this firebase provider during development of my initial MVP and then plan to switch to some scalable graphql based backend later as I worked towards a V1.0 release of my app. Most likely [postgres + elixir + absinthe](https://github.com/absinthe-graphql/absinthe).

There are a few reasons for this - but primarily it is because I think developing with firestore is more productive (from a business perspective) early on but is less flexible (from a business perspective again) later compared to other compiled framework backends.

Given every new business venture essentially goes through a process of converging on a specific feature vertical and then diverging into horizontal supporting features.

So my take on the value of this provider is to provide the foundation for a rapid prototype framework for working with react-admin to get an MVP up and running for a prospective idea.

Whether the provider provides more complex generic app features that you would expect in a batteries included framework is debatable. Once could argue that the provider should focus on core CRUD functionality and push out other functions into another project that builds on top of it. Or one could just say the provider has 2 modes - basic and advanced.

I suppose this also comes back to what the opinion of the react-admin team is in regards to basic functionality?

**Comment by RWOverdijk** [comment]
This. We have a couple thousand records in multiple collections now and it's becoming expensive real quick.

In terms of "the number of records" a meta field could be made that keeps track of this. It's a common approach [using FieldValue.increment](https://fireship.io/snippets/firestore-increment-tips/). As with the other (recent) additions to this library I think it should be optional as it adds logic to your data that otherwise wouldn't exist. This is a very important feature though as otherwise this causes a dashboard to have a TTL.

Regarding fuzzy-search, this would be a trade-off that can easily be re-enabled using something like [algolia](https://firebase.google.com/docs/firestore/solutions/search) if really needed. We're almost never using fuzzy search for example, so it wouldn't be a huge deal.

Maybe this can be a group effort? We can invest some time in this, anyone up to help?

**Comment by RWOverdijk** [comment]
A crazy idea would be to use something like [WatermelonDB](https://nozbe.github.io/WatermelonDB/Advanced/Sync.html) to keep a local copy... We'd get all the features needed and it will feel fast.

**Comment by RWOverdijk** [comment]
We have now created a `--stats--` collection which holds metadata for all the other collections, such as the document count. All this really required were two hooks (create, delete) to maintain the counter.

Using this we can now start paginating the results. As to fuzzy search we've also made our own solution, which is a large document that contains everything that is searchable. We're well below 2kb and the limit of a doc is 1mb, so this is perfect. Also means there's only 1 read for fuzzy search where it's needed.

@benwinding do you have pointers as to how we could implement the pagination part on top/inside of this library?

**Comment by agentlewis** [comment]
Would you be willing to share this code? Sounds very much what I was looking for :)

**Comment by RWOverdijk** [comment]
It's a FieldValue increment and decrement. That part is really simple, it's the pagination itself that'll be a challenge. 😅

AS to the fuzzy search it's for out inventory system (we're a marketplace of sorts) and each venue gets a cache doc that we lazy load.

**Comment by benwinding** [comment]
Hi @RWOverdijk ,

> collection which holds metadata for all the other collections, such as the document count. All this really required were two hooks (create, delete) to maintain the counter.

Funny you mention that, I actually answered a [StackOverflow question with that exact method](https://stackoverflow.com/questions/46554091/cloud-firestore-collection-count/59151014#59151014). It's kind of a hack, but seems to work well.

But getting the collection size only helps for getting the maximum number of pages, which isn't totally necessary.

Pagination turns out to be surprisingly complicated in firestore, as we need to store the last pageToken aka [queryCursor](https://firebase.google.com/docs/firestore/query-data/query-cursors), in order to request the next page. This means we can't simply grab page 223 in a collection  of 10,000 documents without first getting the 223 pages...

React-admin uses numerical pagination, which doesn't match firestore's queryCursor, so we either need to save the queryCursor to the database, or to local storage (simpler).

We could link each react-admin URI to it's corresponding query cursor (as we can't save the queryCursor in the URI). The local storage schema could look like the following:

| Resource URI                                            | queryCursor Id   |
|---------------------------------------------------------|------------------|
| users?filter=%7B%7D&order=DESC&page=1&perPage=5&sort=id | asdas09aubfwa9wf |
| users?filter=%7B%7D&order=DESC&page=2&perPage=5&sort=id | 124kn1jl24huhdas |
| users?filter=%7B%7D&order=DESC&page=3&perPage=5&sort=id | 09e21j21iejnoi28 |

And the logic for the pagination might go as follows, where if a `queryCursor` is not found, it will try to find the last query cursor locally and add query to it, till it reaches the current page of data.

![image](https://user-images.githubusercontent.com/11782590/82166728-7d511a80-98f8-11ea-9aab-a99f97d4570d.png)

Link to live version: https://code2flow.com/eMsnXh

Not sure if this makes sense to you guys, but it would be nice to have a solution that doesn't require cloud functions to be deployed.

> Using this we can now start paginating the results. As to fuzzy search we've also made our own solution, which is a large document that contains everything that is searchable. We're well below 2kb and the limit of a doc is 1mb, so this is perfect. Also means there's only 1 read for fuzzy search where it's needed.

I'd be interested in hearing more details about how this works @RWOverdijk

**Comment by RWOverdijk** [comment]
I can see your point. It is an unfortunate model to use with numbered pagination. Even using offset() in a function won't solve anything when it comes to reads...

Can't you just store the cursor value in redux? There's always a last id and as long as there's a sorting set up your results will be predictable. Then there's no need to store a cursor in local storage (which makes it unsharable) or the database (which breaks multi-screen features).

I mean sure, fetch the first 223 pages if needed. It's still less than fetching everything and it's unlikely someone would jump straight to page 223. One such example is orders. Who'd go back in time several months to find an old order? Some might, but then it's still a lot less reads.

> I'd be interested in hearing more details about how this works @RWOverdijk

The fuzzy search? We just have on create, delete and update triggers that keep the "name" in a large array, which we use in the browser for fuzzy search. It won't work for everything but works fine for out specific case.

**Comment by adamf92** [comment]
Hi @benwinding  @RWOverdijk !
I want to ask about progress with this issue, as we also need solution for currently developed application. If you already started implementing it, I think there is no sense for us to do the same things simultaneously. Maybe I can help you with something?

**Comment by RWOverdijk** [comment]
@adamf92 Nothing yet for paging. The more I learn about firebase/firestore the more I regret choosing to use it 😅

**Comment by NishidaRyu416** [comment]
I know it is going to be inconvenient for an admin panel but we can solve the problem with the infinite scroll🤔

Of course, as you must be aware, we may be having trouble with the current implementation for CRUD as it has page transitions: to completely solve this, all the CRUD stuff  has to be done with modals.

**Comment by benwinding** [comment]
> I know it is going to be inconvenient for an admin panel but we can solve the problem with the infinite scroll

@NishidaRyu416 that's an intriguing idea. This would require a new Table component to be implemented, [here's an example](https://codesandbox.io/s/52xz76v5wn?file=/src/messagemanager.js). And would have some trade-offs:
- Search would only work on loaded rows, or require exact match ([see here](https://github.com/benwinding/react-admin-firebase/issues/59#issuecomment-569284598))
- Sorting needs to be done using firestore queries
But it could be an elegant solution to easily browse large datasets, without _High Reads_

@adamf92 I'm still considering options, but will probably begin building something like [this solution here](https://github.com/benwinding/react-admin-firebase/issues/59#issuecomment-629906871)

I want to resist developing anything that requires cloud functions to be deployed or meta-collections in Firestore.... but that might be unavoidable...

**Comment by RWOverdijk** [comment]
@benwinding I think that's maybe not the best idea. You'll get a whole new world of pain if anyone changes a record and your cursors are suddenly wrong. But after trying and spending time on this I came to just one conclusion personally.

I have just accepted that firestore isn't ideal if you're going to have a lot of data. It's fine to get started, but quickly just becomes expensive and difficult to work with. I'm finally ready to stop trying to make it do things it just wasn't built to do. :p

**Comment by benwinding** [comment]
> @benwinding I think that's maybe not the best idea. You'll get a whole new world of pain if anyone changes a record and your cursors are suddenly wrong. But after trying and spending time on this I came to just one conclusion personally.

That's true, there's some drawbacks to the approach I'm not sure cursors changing position slightly is a major problem though. 

I might reconsider using cloud functions with meta collections, which would get close to solving all the problems. However it would mean; _adding countless firestore hooks, reserved collections, and deploying/syncing cloud functions, creating an additional nodejs library_ . It's all this additional complexity that is stopping me from going down this path, but I'll revisit it soon.

> I have just accepted that firestore isn't ideal if you're going to have a lot of data. It's fine to get started, but quickly just becomes expensive and difficult to work with. I'm finally ready to stop trying to make it do things it just wasn't built to do. :p

Yes, I agree. Firestore can be annoying to work with. In an `SQL` database you can make global queries easily referencing all users matching certain conditions. Whereas _Firestore_ makes this annoying by requiring you to build an indexes for more than 1 `where()` query.

I think Firestore is incredibly cheap for what you get and is still a suitable solution for scalable applications, it just just doesn't map to a REST api very well. I was thinking of using a graphql layer between Firestore and react-admin, which would also fix a lot of these problems (caching, paging, searching), but I haven't tried yet....

_(Anyway sorry for the rant, this is more me just thinking to myself lol)_

**Comment by LaszloDev** [comment]
I got frustrated with Firebase also when starting to build a more production ready system.

Now I moved to AWS which offers with AWS Dynamodb some similar NoSQL DB, but you have to setup AWS AppSync manually for an GraphQL API (or write your own from scratch). My problem now is, there is no Data & Authprovider for GraphQL & AWS (AppSync/Cognito) and I have to write it my self.

To sum it up, Firebase together with this lib is great to get started, but if you want to build a serious scaling system, you can’t use a simple out-of-the-box solution like Firebase and expect everything to work. Plus Firebase pricing gets quickly high.
As sad as it sounds, nothing comes without work.

**Comment by agentlewis** [comment]
@LaszloDev on a recent project we used [Amplify](https://aws.amazon.com/amplify/) primarily because of its costing model (just simply: data served + data on disk/month) 

We also really liked the [amplify directives](https://docs.amplify.aws/cli/graphql-transformer/directives) used in combo with auto codegen.

For a production app I would likely use this... However for client POCs and getting stuff done fast Firebase and React-Admin are winners. 

I have also built a firebase cloud function that connects to airtable and use this to just dump data sets into it so clients can run there data queries in there. In theory this would mean something running react-admin-firebase wouldn't also need to be used for exploring data. Only for managing accounts. eg customer support service agents super admin panel for changing customer properties when they are stuck.

keep up the good work @benwinding I'm still planning to use your great library one of these days :)

**Comment by adamf92** [comment]
@benwinding I have ready implementation (with some points to be improved) with cursors saved in storage. I will open PR from my fork later today, when I'll back home. I had to implement it for almost production app and number of reads decreased from 50k daily, to 20-30k weekly

**Comment by benwinding** [comment]
> I have ready implementation (with some points to be improved) with cursors saved in storage. 

Wow thanks @adamf92! Glad to hear you got the reads down, I'll be interested to see your implementation :+1:

**Comment by agentlewis** [comment]
@adamf92 epic effort mate.

On the topic of pagination I would say that from a UX POV is not very good. Infinite scroll is better. Ie scroll triggered next page.

What I mean: knowing the number of pages is pretty useless. What a user wants to know is the number of records that return for a given query. If no filters than return total number of records (relates to cursor tracking as you mentioned)

The other advantage of infinite scroll is a user can change a filter and get an immediate update to the view. 

With paginated views the user will always need to be taken back to the first page after a filter change - making a more bumpy UX transition. Ie the user will feel the view has been reset rather than just been filtered. 

With an infinite scroll approach the client would optimistically update the UI based on the filtered derived state. In the background it would query the server with the filters and be looking for the results of everything AFTER the provided cursor. (If i have understood how cursors are working).

Alternatively you could just sync the client collection (ie fetching new items after the provided cursor) every time you run a filter.

The second option is probably the better of the two. It would mean a large number of downloads the first time a collection is viewed. 

You could further optimise this to reduce reads to as needed rather than minimum one every query.

Excited to see your ideas for this 😊

**Comment by RWOverdijk** [comment]
I like that. A user will almost never look for a specific page number, and will much sooner use search or filters. So in terms of pagination I'd say an infinite scroll (with one of those "click to load more" fallbacks) would do the trick.

Same features, less reads. I'd say it's pretty clever. It deviates from react-admin so I think it should work as a plugin of sorts though. Allow for the regular ra List to be used, or the InfinitList from ra-firebase to be used for infinite scrolling.

I like this! 😄

**Comment by agentlewis** [comment]
@RWOverdijk on the deviating from react-admin noticing. From my POV if the react-admin design methodology is using paginated views for tables they are behind the times and its just a question of when they update this to infinite scroll.

Airtable has already proven that you can do infinite scroll with tables really well and I'd say essentially proven this to be a better UX for customers. I just opened a table with 1500 rows in it, it loaded them in chunks of 50 and was very very fast. (obviously using a cdn and other performance-ware). I think the computer was the limiting factor in rendering them fast enough.

**Comment by RWOverdijk** [comment]
I get that, and this would probably use virtualized lists of sorts to keep things snappy.

I agree with you, but I still think it should be a differently named component.
