### ISSUE TITLE
Overriding ID behavior 

### ISSUE THREAD

**Issue by dhstack** [benwinding/react-admin-firebase#77]
As the [code is currently written](https://github.com/benwinding/react-admin-firebase/blob/9b1ca53f43e757eb1654df3a80a16e169fcbe0be/src/providers/database/FirebaseClient.ts#L70), if the document ID is overridden, but it already exists then a new ID is auto generated.

This is a bit confusing, because part of the reason one may want to override the document ID is to create documents with that ID pattern for easier querying AND **enforce unique IDs**.

As such, by default, if an ID is being manually overridden it may be better to throw an error instead of automatically using an auto-generated Firestore ID. Otherwise, there's no way to ensure unique IDs.

**Comment by benwinding** [comment]
Hey @dhstack,

So this has been fixed in PR #86. Now instead of overwriting a document it throws an error if the id already exists. 

However there's another problem, when the `DataProvider` throws the error (Rejected promise) it logs you out?? I think there's a problem with `react-admin` interacting with this provider, as it's a legacy provider format now.

Anyway this is deployed in `react-admin-firebase@3.1.0`

Cheers,
Ben

**Comment by dhstack** [comment]
@benwinding Yes, it's logging me out too. I created a separate issue for that, #91.

Also, I saw that you [added an option for `overrideDefaultId`](https://github.com/benwinding/react-admin-firebase/blob/master/src/providers/RAFirebaseOptions.ts), but it [doesn't seem to be used anywhere](https://github.com/benwinding/react-admin-firebase/search?q=overrideDefaultId&unscoped_q=overrideDefaultId) else besides the options?

**Comment by benwinding** [comment]
Hi @dhstack,

Yes that option hasn't been implemented yet but the idea was to be able to assign a different property from Firestore to the id in the URL. For example:

This Firestore document lives at `vehicles/GrIoqSAts4f0sFl0QVHV`
``` json
{
   "NumberPlate": "ABC123"  
}
```
``` bash
# Instead of using the docId
url = vehicles/GrIoqSAts4f0sFl0QVHV/show
# Use a property on the document
url = vehicles/ABC123/show
```
There's a few challenges here though and possible collisions, which I'm not sure will be worth it. For example, referencing a document by property rather than docId requires a where query, which will return all documents that match that property.

Could possibly move it to a new issue.

Cheers,
Ben

**Comment by dhstack** [comment]
@benwinding Thanks for clarifying. I like the concept of prettier URLs and the flexibility this option could provide, but it may over-complicate things. I mean wouldn't it be better just to set the docId as the number plate in the first place? That way there's no way for duplicate vehicles to be added by accident.

For me at least, I'm happy with the URL using the docId.
